hours_worked=(int(input("Ingrese las horas trabajadas: ")))
price_hour=(float(input("Ingrese el precio por hora de trabajo: ")))
pay=(hours_worked*price_hour)
discount=(pay*0.18) 
total=(pay-discount)
print("===========================================================================")
print(f"Su pago por horas trabajadas son: {pay} bs.")
print(f"Descuento por IVSS y Banavih {discount} bs.")
print(f" >> Su total a cobrar es: {total} bs.<< ")
print("===========================================================================")